name: Run V2Ray

on: workflow_dispatch

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Setup V2Ray
        uses: bsisnsvsj/setup-v2ray@main
        with:
          config-base64: |
            ewogICJpbmJvdW5kcyI6IFsKICAgIHsKICAgICAgInBvcnQiOiAxMDgwLAogICAgICAibGlzdGVuIjogIjEyNy4wLjAuMSIsCiAgICAgICJwcm90b2NvbCI6ICJzb2NrcyIsCiAgICAgICJzZXR0aW5ncyI6IHsKICAgICAgICAiYXV0aCI6ICJub2F1dGgiLAogICAgICAgICJ1ZHAiOiB0cnVlLAogICAgICAgICJpcCI6ICIxMjcuMC4wLjEiCiAgICAgIH0KICAgIH0KICBdLAogICJvdXRib3VuZHMiOiBbCiAgICB7CiAgICAgICJwcm90b2NvbCI6ICJ2bWVzcyIsCiAgICAgICJzZXR0aW5ncyI6IHsKICAgICAgICAidm5leHQiOiBbCiAgICAgICAgewogICAgICAgICAgImFkZHJlc3MiOiAiZ2l0aHViLmNvbSIsCiAgICAgICAgICAicG9ydCI6IDQ0MywKICAgICAgICAgICJ1c2VycyI6IFsKICAgICAgICAgICAgewogICAgICAgICAgICAgICJpZCI6ICIxNDU3NWUyNS1lNjhmLTQzMzktYWJiZC01ZWFmNjY3MGFmNTgiLAogICAgICAgICAgICAgICJhbHRlcklkIjogMCwKICAgICAgICAgICAgICAic2VjdXJpdHkiOiAiYXV0byIKICAgICAgICAgICAgfQogICAgICAgICAgXQogICAgICAgIH1dCiAgICAgIH0sCiAgICAgICJzdHJlYW1TZXR0aW5ncyI6IHsKICAgICAgICAibmV0d29yayI6ICJ0Y3AiLAogICAgICAgICJzZWN1cml0eSI6ICJ0bHMiCiAgICAgIH0KICAgIH0KICBdCn0=

      - name: Show Public IP
        run: curl ifconfig.me

      - name: Keep alive
        run: sleep 21600
